baseURL = "http://mateus.great-site.net/"
title = "Mateus Felipe Gonçalves"
theme = "papermod"

[[menu.main]]
name = "Archive"
url = "archive"
weight = 1

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.main]]
name = "Search"
url = "search/"
weight = 4

[[menu.main]]
name = "Links"
url = "/mylinks.html"
weight = 5


[params.profileMode]
enabled = true
imageUrl = "https://avatars1.githubusercontent.com/u/40613276?v=4"
imageWidth = 120
imageHeight = 120
ShowShareButtons = true
ShowReadingTime = true


	[[params.profileMode.buttons]]
  name = "About"
  url = "/about"

  [[params.profileMode.buttons]]
  name = "Blog"
  url = "/posts"


[[params.socialIcons]]
name = "Github"
url = "https://github.com/mateusfg7"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/mateusfg7"

[[params.socialIcons]]
name = "Linkedin"
url = "https://linkedin.com/in/mateusfg"


[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/mateusfg77"
